version: '3.5'
services:
  app:
    image: ${TEST_IMAGE_NAME:-jimsihk/alpine-moodle:local}
    build: .
    environment:
      - SITE_URL=http://app:8080
      - MOODLE_SITENAME=Dockerized_Moodle
      - SESSION_CACHE_TYPE=redis
      - SESSION_CACHE_HOST=redis
      - SESSION_CACHE_PORT=6379
      - AUTO_UPDATE_MOODLE=false
      - UPDATE_MOODLE_CODE=false
      - DB_TYPE=pgsql
      - DB_HOST=pgbouncer
      - DB_PORT=5432
      - DB_NAME=moodle
      - DB_USER=moodledbuser
      - DB_PASS=moodledbpass
      - DB_DBHANDLEOPTIONS=true
      - DB_FETCHBUFFERSIZE=0
    depends_on:
      - postgres
      - redis
      - pgbouncer

  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_PASSWORD=moodledbpass
      - POSTGRES_USER=moodledbuser
      - POSTGRES_DB=moodle

  pgbouncer:
    image: bitnami/pgbouncer:1.19.1
    environment:
      - POSTGRESQL_USERNAME=moodledbuser
      - POSTGRESQL_PASSWORD=moodledbpass
      - POSTGRESQL_HOST=postgres
      - PGBOUNCER_DATABASE=moodle
      - PGBOUNCER_AUTH_TYPE=scram-sha-256
      - PGBOUNCER_POOL_MODE=session
      #- ADMIN_USERS=moodledbuser
      - PGBOUNCER_IGNORE_STARTUP_PARAMETERS=options,extra_float_digits
      - PGBOUNCER_PORT=5432
    ports:
      - "5432:5432"
    depends_on:
      - postgres

  redis:
    image: redis/redis-stack-server

  sut:
    image: alpine:latest
    depends_on:
      - app
    environment:
      - SOURCE_BRANCH
    command: /tmp/run_tests.sh
    volumes:
      - "./run_tests.sh:/tmp/run_tests.sh:ro"
