#!/bin/sh
#
# Moodle version checking script
# Description: The script will take the inputted Git commit hash to compare 
#              with the current version, returning error if different
#

if [ -n "$1" ]
then
  MOODLE_VERSION=$(grep "\$version" "${WEB_PATH}"/version.php | sed 's/ //g' | cut -d';' -f1 | cut -d '=' -f2)
  echo "Downloaded Moodle version: $MOODLE_VERSION"
  /usr/libexec/check-git-commit "${WEB_PATH}" "$1"
  exit $?
else
  echo "Missing argument: <target commit hash>"
  exit 2
fi