#!/bin/sh
#
# Moodle code plugin installation wrapper script
# Description: The script will execute install-plugin-list script with some custom logic
#

UTL_PATH=/usr/libexec/moodle

# Install additional plugins (a space/comma separated argument), if any
# Reference: https://github.com/krestomatio/container_builder/tree/master/moodle#moodle-plugins
if [ -n "${MOODLE_PLUGIN_LIST}" ]; then
  if [ -n "${ALLOW_INCOMPATIBLE_PLUGIN}" ] && [ "${ALLOW_INCOMPATIBLE_PLUGIN}" = 'true' ]; then
    "$UTL_PATH"/install-plugin-list -f -p "${MOODLE_PLUGIN_LIST}";
  else
    "$UTL_PATH"/install-plugin-list -p "${MOODLE_PLUGIN_LIST}";
  fi
fi
rm -rf /tmp/moodle-plugins
