#!/bin/sh
#
# Moodle code download script
# Description: The script will unpack the required Moodle source codes 
#              and plugin source codes
#              1. Download Moodle source
#              2. Install system plugins
#              3. Install custom plugins
#

UTL_PATH=/usr/libexec/moodle

# 1. Download Moodle source
#
# Install from Git for easier upgrade in the future
# - Using temporary storage to store the Git repo and copy back to working directory 
#   to avoid detached head and failure due to files exist in the directory
# - Git depth is set to 1 and and single branch to reduce docker size while keeping
#   the functionality of git pull from source
TEMP_MOODLE_PATH='/tmp/moodle'
if [ -d "${TEMP_MOODLE_PATH}" ]; then
  rm -rf "${TEMP_MOODLE_PATH}";
fi
echo "Clone from official Moodle git repo"
git clone "${MOODLE_GIT_URL}" --branch "${MODOLE_GIT_BRANCH}" --single-branch --depth 1 "${TEMP_MOODLE_PATH}"/
# Remove unused files which are difficult to hide by Nginx config
if [ -f "${TEMP_MOODLE_PATH}"/Gruntfile.js ]; then
  rm "${TEMP_MOODLE_PATH}"/Gruntfile.js;
fi
if [ -f "${TEMP_MOODLE_PATH}"/config-dist.php ]; then
  rm "${TEMP_MOODLE_PATH}"/config-dist.php;
fi
echo "Copying from ${TEMP_MOODLE_PATH} to ${WEB_PATH}..."
cp -paR "${TEMP_MOODLE_PATH}"/. "$WEB_PATH"/
echo "Cleaning up ${TEMP_MOODLE_PATH}..."
rm -rf "${TEMP_MOODLE_PATH}"
# Verify Moodle version if same as specified in DockerFile
"$UTL_PATH"/check-moodle-version "${MOODLE_GIT_COMMIT}"

# 2. Install system plugins
#
# Install plugin for Redis Sentinel cache store
# Reference: https://github.com/catalyst/moodle-cachestore_redissentinel
"$UTL_PATH"/install-git-plugin \
  "${REDISSENTINEL_PLUGIN_GIT_URL}"  \
  "${REDISSENTINEL_PLUGIN_GIT_BRANCH}" \
  "${REDISSENTINEL_PLUGIN_GIT_COMMIT}" \
  "${WEB_PATH}/cache/stores/redissentinel/"
# Install plugin for memcached cache store which was removed from Moodle core since 4.2
# Reference: https://tracker.moodle.org/browse/MDL-77161
"$UTL_PATH"/install-git-plugin \
  "${MEMCACHED_PLUGIN_GIT_URL}" \
  "${MEMCACHED_PLUGIN_GIT_BRANCH}" \
  "${MEMCACHED_PLUGIN_GIT_COMMIT}" \
  "${WEB_PATH}/cache/stores/memcached/"

# 3. Install custom plugins
#
# Install additional plugins (a space/comma separated argument), if any
# Reference: https://github.com/krestomatio/container_builder/tree/master/moodle#moodle-plugins
if [ -n "${MOODLE_PLUGIN_LIST}" ]; then
  "$UTL_PATH"/install-plugin-list -p "${MOODLE_PLUGIN_LIST}";
fi
rm -rf /tmp/moodle-plugins
