#!/bin/sh
#
# Install Moodle plugin from Git
# Description: The script will take the inputted Git repo to install 
#              to Moodle core
# Parameters: $1: Git repo URL, e.g. https://github.com/catalyst/moodle-cachestore_redissentinel.git
#             $2: Git branch, e.g. master
#             $3: Git commit hash, e.g. b495e8f36a81fd1a2a414e34a978da879c473f31
#             $4: Moodle plugin absolute path, e.g. /var/www/html/cache/stores/redissentinel/
#

if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ]
then
  PLUGIN_GIT_URL="$1"
  PLUGIN_GIT_BRANCH="$2"
  PLUGIN_GIT_COMMIT="$3"
  PLUGIN_PATH="$4"
  /usr/libexec/clone-from-git "${PLUGIN_GIT_URL}" "${PLUGIN_GIT_BRANCH}" "${PLUGIN_GIT_COMMIT}" "${PLUGIN_PATH}"
else
  echo "Missing argument: <repo> <branch> <commit_hash> <local_path>"
  exit 1
fi