#!/bin/sh
#
# Clone Git Repository with Minimal Commit History
# Description: The script will take the inputted Git repo to clone the repo with least commit history
# Parameters: $1: Git repo URL, e.g. https://github.com/catalyst/moodle-cachestore_redissentinel.gi
#             $2: Git branch, e.g. master
#             $3: Git commit hash, e.g. b495e8f36a81fd1a2a414e34a978da879c473f31
#             $4: Moodle plugin absolute path, e.g. /var/www/html/cache/stores/redissentinel/
#

if [ -n "$1" ] && [ -n "$2" ] && [ -n "$3" ] && [ -n "$4" ]
then
  INPUT_GIT_URL="$1"
  INPUT_GIT_BRANCH="$2"
  INPUT_GIT_COMMIT="$3"
  DOWNLOAD_PATH="$4"
  echo "Clone from git repo: ${INPUT_GIT_URL}..."
  git clone "${INPUT_GIT_URL}" --branch "${INPUT_GIT_BRANCH}" --single-branch --depth 1 "${DOWNLOAD_PATH}"/
  # Make sure the current HEAD is the defined commit
  for FETCH_DEPTH in 1 5 10 30 50 100 200
  do
    if [ $FETCH_DEPTH -gt 1 ]
    then
      echo "Attempting to fetch last $FETCH_DEPTH commits..."
      git -C "${DOWNLOAD_PATH}" fetch origin "${INPUT_GIT_BRANCH}" --depth "${FETCH_DEPTH}"
    fi
    git -C "${DOWNLOAD_PATH}" reset --hard "${INPUT_GIT_COMMIT}"
    RESULT=$?
    if [ $RESULT -eq 0 ]
    then
      break;
    fi
  done
  git -C "${DOWNLOAD_PATH}" clean -dfx
else
  echo "Missing argument: <repo> <branch> <commit_hash> <local_path>"
  exit 1
fi